Models/ErrorViewModel.cs
namespace Mvc101.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Mvc101.Controllers
{
    public class FilesController : Controller
    {
        // GET: Process
        public ActionResult Index()
        {
            string[] files = Directory.GetFiles("TextFiles").Select(f=> Path.GetFileName(f)).ToArray();
            ViewBag.Files = files;
            return View();
        }

        public ActionResult Content(string id) {
            string[] f = System.IO.File.ReadAllLines(Directory.GetCurrentDirectory() + "/TextFiles/" + id);
            return View(f);
        }
        

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mvc101.Models;

namespace Mvc101.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    //constructor
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        string[] days = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
        ViewData["days"] = days;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Bogus()
    {
        string[] days = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
        ViewData["author"] = "Jane Bond";
        ViewBag.Date = DateTime.Now;
        return View(days);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Mvc101.Controllers
{
    public class ProcessController : Controller
    {
        // GET: Process
        public ActionResult Index()
        {
            return View(Process.GetProcesses());
        }

        public ActionResult Display(int id) {
            
            return View(Process.GetProcessById(id));
        }

    }
}

Views/Files/Content.cshtml
@model string[]

@{
    ViewData["Title"] = "File Content";
}


<div>
    <ul>
        @foreach(var item in Model) {
            <li>
                @item
            </li>
        }

    </ul>
</div>

Views/Files/Index.cshtml
@{
    ViewData["Title"] = "Files Page";
    var files = ViewBag.Files as string[];
}

<div class="text-center">
    <h1 class="display-4" style="color: tomato;">Files to be added</h1>


</div>

<div>
    <ul>
        @foreach(var item in files!) {
            <li><a asp-controller="Files" asp-action="Content" asp-route-id="@item">@item</a></li>
        }
    </ul>

</div>

Views/Home/Bogus.cshtml
@model string[] //what object to expect
@{
    ViewData["Title"] = "Bogus Page";
    var date = (System.DateTime) ViewData["Date"]!;
}
<h1>@ViewData["Title"]</h1>

<p>This is my first ASP.NET page authored by @ViewData["author"] on @date.ToShortTimeString()</p>

<ul>
@foreach (var item in Model) {
    <li>@item</li>
}
</ul>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    string[]? days = ViewData["days"] as string[];
}

<div class="text-center">
    <h1 class="display-4" style="color: tomato;">Gangmin Bae A01274381</h1>

    <h2>Any Job that pay me well</h2>
</div>

Views/Process/Display.cshtml
@model System.Diagnostics.Process

@{
    ViewData["Title"] = "Process Details";
}


<div>
    <table>

        <tr>
            <td>
                ID:
            </td>
            <td>
                @Model.Id
            </td>

        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Model.ProcessName
            </td>

        </tr>
        <tr>
            <td>
                Count:
            </td>
            <td>
                @Model.HandleCount
            </td>

        </tr>
    </table>
</div>

Views/Process/Index.cshtml
@model System.Diagnostics.Process[]

@{
    ViewData["Title"] = "Processes";
} 

<div>
    <h2>@ViewData["Title"]</h2>
    <ul>
        @foreach(var item in Model) {
            if(item.ProcessName.Trim().Length > 0) {
                 <li><a asp-controller="Process" asp-action="Display" asp-route-id="@item.Id">@item.ProcessName</a></li>
            }
            
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc101</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc101.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc101</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mvc101 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>